INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 11, 'ASSAULT WEAPON');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 12, 'ASSAULT NO WEAPON');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 15, 'CHILD ABUSE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 16, 'THEFT FROM PERSON');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 17, 'HOLD-UP ALARM');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 19, 'ROB COMERCIAL');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 22, 'ROB PERSON');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 26, 'MISSING PERSON');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 27, 'MISSING CHILD');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 28, 'UNATTENDED/FOUND CHILD');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 29, 'SUICIDE/ATTEMPTED SUICIDE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 32, 'PANIC ALARM');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 11, 'TERRORISTIC THREATS');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 12, 'INTERFERE W/ CUSTODY');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 14, 'HARASSMENT(VERBAL ABUSE)');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 15, 'TELEPHONE HARASSMENT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 18, 'TENANT/LANDLORD DISPUTE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 19, 'PUBLIC ARGUMENT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 21, 'MERCHANT/CUSTOMER DISPUTE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 22, 'PREVENT BREACH OF PEACE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 23, 'OTHER INTER/CONFLICT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 11, 'DAMAGE TO PUBLIC PROPERTY');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 12, 'DAMAGE RESIDENTIAL');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 13, 'DAMAGE COMMERICIAL');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 14, 'DAMAGE MOTOR VEHICLE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 15, 'DAMAGE OTHER PROP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 16, 'TRESPASS');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 18, 'BURGLARY RESIDENTIAL PROP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 19, 'BURGLARY COMERCIAL PROP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 21, 'BURGLARY OTHER STRUCTURE/AREA');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 22, 'THEFT PROP FROM VEHICLE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 23, 'THEFT OF SERVICE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 24, 'THEFT OTHER PROP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 25, 'SHOPLIFTING');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 27, 'MOTOR VEHICLE THEFT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 28, 'BURG ALARM PUBLIC PROP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 29, 'BURG ALARM RESIDENTIAL PROP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 31, 'BURG ALARM COMMERCIAL PROP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 32, 'BURG ALARM MOTOR VEHICLE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 33, 'BURG ALARM OTHER');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 35, 'OTHER PROP CRIME');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 36, 'FRAUD');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 11, 'MOTOR VEHICLE ACCIDENT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 12, 'MOTOR VEHICLE RUNNING UNATTENDED');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 13, 'PEDESTRIAN STRUCK');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 14, 'HIT AND RUN (PERSON STRUCK )');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 15, 'LEAVING THE SCENE OF A ACCIDENT ( PROPERTY DAMAGE ONLY )');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 16, 'SIGN DOWN/TRAFFIC LIGHT OUT OF ORDER');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 17, 'INTOXICATED DRIVER');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 18, 'RACING/SPEEDING/CARELESS DRIVING');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 19, 'TRAFFIC CONGESTION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 21, 'HYDRANT PARKING VIOLATION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 22, 'CROSSWALK PARKING VIOLATION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 23, 'DRIVEWAY PARKING VIOLATION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 24, 'OTHER PARKING VIOLATION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 25, 'ABANDONED/APPARENT STOLEN');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 26, 'ROADWAY OBSTRUCTION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 28, 'NO CITY PERMIT PARKING VIOLATION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 29, 'DISABLED VEHICLE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 31, 'OTHER VEHICLE/TRAFFIC PROBLEM');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 34, 'HANDICAPPED PARKING');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 11, 'DISORDERLY CONDUCT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 12, 'NOISE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 13, 'LOUD MUSIC');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 14, 'STREET FIGHT ( NO WEAPONS )');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 15, 'LOITERING');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 16, 'INTOXICATED PERSON');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 17, 'FIREWORKS');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 18, 'STREET GAMES');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 21, 'OTHER PUBLIC NUISANCE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 11, 'PROWLER');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 12, 'TAMPERING WITH A VEHICLE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 13, 'HAZARDOUS CONDITION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 14, 'BOMB THREAT PUBLIC BUILDING/PLACE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 15, 'BOMB THREAT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 16, 'SUSPICIOUS PERSON/CONDITION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 17, 'EXPLOSIVE DEVICE FOUND');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 18, 'GUNSHOTS FIRED HEARD ( NO WITNESS / VICTIM )');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 19, 'PERSON SCREAMING / CALLING FOR HELP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 21, 'SLUMPER IN VEHICLE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 22, 'OPEN 9-1-1  TELEPHONE LINE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('F', 23, 'OTHER SUSPICIOUS/HAZARDOUS CIRCUMSTANCES');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('G', 11, 'LEWDNESS');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('G', 12, 'PROSTITUTION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('G', 13, 'USE/SALE OF DRUGS');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('G', 18, 'FIREARM PERSON WITH');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('G', 19, 'WEAPON PERSON WITH');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('G', 22, 'FOUND WEAPON');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('G', 23, 'FOUND CDS/PARAPHERNALIA');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 11, 'OFFICER NEEDS ASSISTANCE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 12, 'HOLDING ACTOR');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 13, 'AMBULANCE REQUEST FOR');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 14, 'FIRE / EXPLOSION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 17, 'ODOR OF GAS / TOXIC SPILL');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 19, 'CC CITIZEN');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 21, 'UTILITY BREAK / INTERRUPTION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 22, 'ANIMAL COMPLAINT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 23, 'LOST / MISLAID PROPERTY');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 24, 'NOTIFICATION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 25, 'TRANSPORTATION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 28, 'MEET OTHER AGENCY');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 29, 'DEAD BODY');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 31, 'PERSON DOWN/CAUSE UNKNOWN');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 32, 'CHECK WELFARE OF');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 33, 'ELEVATOR STUCK W/OCCUPANTS');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 34, 'INDUSTRIAL / CONSTRUCTION MISHAP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 35, 'OTHER ASSISTANCE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 11, 'VEHICLE SERVICE SHOP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 12, 'COURT OFF AT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 13, 'PERSONAL OFF ON');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 14, 'MEAL');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 15, 'RANGE OF AT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 16, 'CAR WASH');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 17, 'DISTRICT MISSION / ASSIGNMENT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 18, 'MAIL PICK UP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 19, 'SCHOOL CROSSING');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 21, 'TRAFFIC POST');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 22, 'WARRANT SERVICE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 23, 'DISABLED POLICE VEHICLE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 24, 'DIRECTED PATROL');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 25, 'WARRANT ARREST');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 26, 'OTHER ADMIN POLICE ACTIVITY');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 27, 'COMMUNITY MEETING');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 28, 'PRISONER WATCH');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 29, 'OFF on INVESTIGATION');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 31, 'SERVING RESTRAINING / COURT ORDER');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('T', 10, 'TRAFFIC STOP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('Z', 0, 'REFERRED TO ANOTHER AGENCY');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('Z', 33, 'RING BACK');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('Z', 58, 'CELL FALSE 911');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 16, 'LABOR DISPUTE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('G', 14, 'GAMBLING');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('G', 21, 'OTHER PUBLIC MORALS OFFENSES');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('B', 17, 'NEIGHBOR DISPUTE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 21, 'ROB FINANCIAL');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 34, 'BAD CHECK/CREDIT CARD');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 26, 'POSSESSION STOLEN PROP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('Z', 66, 'FALSE 9-1-1 CALL');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('D', 27, 'NO TRUCKING STREET');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 25, 'HOSTAGE/BARRICAD SUSPECT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('E', 19, 'STRANGE ODOR');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 31, 'OTHER PERSON CRIME');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 18, 'ROB AT RESIDENCE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('C', 17, 'BURGLARY PUBLIC PROP');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('Z', 77, 'BAD CALL CODE/DATA');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 26, 'ASSIST INVALID');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('Z', 56, 'BAD ADDRESS FR PHONE CO');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('Z', 44, 'OTHER CALL TAKER ADJUSTED PHONE CALL');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('J', 32, 'PSN - Project Safe Neighborhoods');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('Z', 67, 'VOIP FALSE 911 (VOICE OVER INTERNET)');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('A', 24, 'HOMICIDE');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('Z', 88, 'TESTING CODES FOR MDC TRAINING');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 16, 'ESCORT WIDE LOAD/CONSTRUCTION EQUIPMENT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 27, 'COUNTY JAIL DISTURBANCE AT');
INSERT INTO public.call_codes (type, pd_code, description) VALUES ('H', 36, 'SKYWAY CLOSURE');